import NextBreadcrumb from '@/component/NextBreadcrumb'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextBreadcrumb
          homeElement={'Home'}
          separator='/'
          separatorClasses='mx-2'
          containerClasses='flex'
          listClasses='hover:underline'
        />
        {children}
      </body>
    </html>
  )
}
